ecommerce_dbt_project:
  outputs:
    dev:
      dataset: ecommerce_dbt
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: C:\Users\talit\OneDrive\Documentos\Teste\serene-craft-466220-m7-475b1869b0d2.json
      location: US
      method: service-account
      priority: interactive
      project: serene-craft-466220-m7
      threads: 1
      type: bigquery
  target: dev

